# Application
spring.application.name=libraryapi

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/libraryapi
spring.datasource.username=libraryapi
spring.datasource.password=libraryapi

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
