CREATE TABLE books (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    author            VARCHAR(255) NOT NULL,
    isbn              VARCHAR(17) NOT NULL UNIQUE,
    publication_year  INTEGER NOT NULL,
    genre             VARCHAR(100) NOT NULL,
    available         BOOLEAN NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
